server:
  port: 8989
logging:
  level:
    root: info
spring:
  profiles:
    active: prod  # prod dev
  session:
      store-type: redis
      timeout: PT30M
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:
      - classpath:/static/
  datasource:
    druid:
      stat-view-servlet:
        enabled: true   # 开启 默认false
        url-pattern:
          - /druid/*    # 监控的地址
        login-username: druid
        login-password: druid

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml
  #config-location: classpath:mapping/config.xml # 主配置文件
  type-aliases-package: com.lksun.library.entity # 作用:在mapper.xml中resultType属性就无须写完整的包路径了只需要写一个类名