server:
  port: 8989
logging:
  level:
    root: info
spring:
  redis:
    host: localhost
    timeout: PT30M #30分钟
  session:
      store-type: redis
      timeout: PT30M
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:
      - classpath:/static/
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/demo
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  # 修改配置源
    schema:
      - classpath:demo.sql    # 构建数据
    initialization-mode: always
    druid:
      stat-view-servlet:
        enabled: true   # 开启 默认false
        url-pattern:
          - /druid/*    # 监控的地址
        login-username: druid
        login-password: druid

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml
  #config-location: classpath:mapping/config.xml
  type-aliases-package: com.lksun.library.entity