server:
  port: 8989
spring:
  redis:
    host: localhost
    timeout: PT30M #30分钟
  session:
      store-type: redis
      timeout: PT30M
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations:
      - classpath:/static/
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/demo
    driver‐class‐name: com.mysql.jdbc.Driver
    schema:
      - classpath:data.sql
    initialization-mode: always
logging:
  level:
    root: info